using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SLBFE.Models
{
    /// <summary>
    /// The complaint Object
    /// </summary>
    public class Complaint
    {
        /// <summary>
        /// Autogenerated ID for the Complaint
        /// </summary>
        public string ComplaintID { get; set; }

        /// <summary>
        /// Email of the user that sent this
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Username of the user that sent this
        /// </summary>
        public string Username { get; set; }

        /// <summary>
        /// is This a Complaint or Feedback
        /// </summary>
        public bool isComplaint { get; set; }

        /// <summary>
        /// Company Email that is related to this
        /// </summary>
        public string CompanyID { get; set; }

        /// <summary>
        /// Company Name that is related to this
        /// </summary>
        public string CompanyName { get; set; }

        /// <summary>
        /// Which dated that this sent
        /// </summary>
        public DateTime SentDate { get; set; }

        /// <summary>
        /// Content of ths complaint
        /// </summary>
        public string Content { get; set; }

    }

    /// <summary>
    /// Object for the complaint Reply
    /// </summary>
    public class ComplaintReply
    {
        /// <summary>
        /// ID of the Complaint that related to reply
        /// </summary>
        public string FeedbackID { get; set; }

        /// <summary>
        /// Who sent this reply
        /// </summary>
        public string Email { set; get; }

        /// <summary>
        /// Who Sent this reply
        /// </summary>
        public string Username { set; get; }

        /// <summary>
        /// When this reply was sent
        /// </summary>
        public DateTime SentDate { get; set; }

        /// <summary>
        /// Content of the reply
        /// </summary>
        public string Content { get; set; }
    }
}